name: CI Pipeline - Build & Test (DockerHub)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'              # Only activates if changes the code from paths
      - '.github/workflows/**'

jobs:
  # Testing pipelines
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install flask pytest

      - name: Run Dummy Tests
        run: echo "Tests passed successfully"

  # Package building requirement
  build-and-push:
    needs: test-code  # Doesn't run until the code is tested
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          # Secrets from github
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          # Image
          tags: ${{ secrets.DOCKER_USERNAME }}/my-final-project:latest